name: "Code Tracks"
description: "Learning Leaves a Trail"

url: "http://codetracks.net"
assets: "/assets"

paginate: 10

markdown: redcarpet
permalink: /:year/:month/:title/
timezone: US/Eastern

highlighter: pygments
gems:
  - jemoji